spring:
  application:
    name: picker-user
dubbo:
  application:
    name: picker-user
    owner: xuliangliang
  scan:
    base-packages: com.grasswort.picker.user.controller
  protocol:
    name: dubbo
    port: 20880
    serialization: kryo
  registry:
    address: nacos://nacos.grasswort.com:8848
  consumer:
    check: false
nacos:
  config:
    server-addr: nacos://nacos.grasswort.com:8848
    namespace: 714709d9-ff45-4e48-873f-f468f3dd90ad

swagger:
  enabled: true
  title: Picker-User 接口文档
  contact:
    name: xuliangliang
    email: 835547206@qq.com
  base-package: com.grasswort.picker.user.controller
  authorization:
    key-name: access_token
  version: 1.0.0



