dubbo:
  application:
    name: picker-user
    owner: xuliangliang
  protocol:
    name: dubbo
    port: 20880
#    serialization: kryo
  config-center:
    address: zookeeper://182.92.3.187:2181?backup=182.92.160.62:2181,39.96.42.239:2181
    group: dubbo
    check: true
#  registry:
#    address: zookeeper://182.92.3.187:2181?backup=182.92.160.62:2181,39.96.42.239:2181
#    simplified: true
#    group: picker-dev
#  consumer:
#    check: false
#  metadata-report:
#    address: zookeeper://182.92.3.187:2181?backup=182.92.160.62:2181,39.96.42.239:2181
#    retry-times: 30
#    cycle-report: false
#    group: picker-dev
#  monitor:
#    address: zookeeper://182.92.3.187:2181?backup=182.92.160.62:2181,39.96.42.239:2181
