dubbo:
  application:
    name: picker-user
    owner: xuliangliang
  config-center:
    address: zookeeper://zookeeper.grasswort.com:2181
    group: dubbo
    check: true
  scan:
    base-packages: com.grasswort.picker.user.controller
#  protocol:
#    name: dubbo
#    port: 20880
#    serialization: kryo
#  registry:
#    address: zookeeper://zookeeper.grasswort.com:2181
#    simplified: true
#    group: picker-dev
#  consumer:
#    check: false
#  metadata-report:
#    address: zookeeper://zookeeper.grasswort.com:2181
#    retry-times: 30
#    cycle-report: false
#    group: picker-dev
#  monitor:
#    protocol: registry
