spring:
  application:
    name: picker-oss
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 10002
  servlet:
    context-path: /api/oss