# dubbo
dubbo:
  application:
    name: picker-blog-service-provider
    owner: xuliangliang
  scan:
    base-packages: com.grasswort.picker.blog.service
  protocol:
    name: dubbo
    port: 20880
    serialization: kryo
  registry:
    address: nacos://nacos.grasswort.com:8848
    check: false
  consumer:
    check: false
# 多数据源配置
multidb:
  defaultGroup: MASTER
  wrappers:
    - group: MASTER
      weight: 1
      dataSource:
        url: jdbc:mysql://114.67.99.146:3306/picker_blog?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
        username: xuliang
        password: xol4l2y2xx
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 2
        minIdle: 1
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,config
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        useGlobalDataSourceStat: true
    - group: SLAVE
      weight: 1
      dataSource:
        url: jdbc:mysql://114.67.84.153:3306/picker_blog?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
        username: xuliang
        password: xol4l2y2xx
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 2
        minIdle: 1
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,config
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        useGlobalDataSourceStat: true
    - group: SLAVE
      weight: 1
      dataSource:
        url: jdbc:mysql://114.67.104.148:3306/picker_blog?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
        username: xuliang
        password: xol4l2y2xx
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 2
        minIdle: 1
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,config
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        useGlobalDataSourceStat: true
    - group: SLAVE
      weight: 1
      dataSource:
        url: jdbc:mysql://192.168.0.3:3306/picker_blog?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
        username: xuliang
        password: xol4l2y2xx
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 2
        minIdle: 1
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,config
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        useGlobalDataSourceStat: true
# quartz 数据源
quartz:
  datasource:
    url: jdbc:mysql://114.67.99.146:3306/picker_quartz?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: xuliang
    password: xol4l2y2xx
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
# quartz 配置
spring:
  quartz:
    auto-startup: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    overwrite-existing-jobs: false
    properties:
      org:
        quartz:
          scheduler:
            # 同一个集群下的实例 instanceName 必须一致
            instanceName: clusteredScheduler
            # AUTO 就是最好的选择
            instanceId: AUTO
          jobStore:
            # 数据源名称
            dataSource: quartzDataSource
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            # 开启集群
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

