dubbo:
  application:
    name: picker-user-service-provider
    owner: xuliangliang
  config-center:
    address: zookeeper://zookeeper.grasswort.com:2181
    group: dubbo
    check: true
  scan:
    base-packages: com.grasswort.picker.user.service
  protocol:
    name: dubbo
    port: 20880
    serialization: kryo
  registry:
    address: zookeeper://zookeeper.grasswort.com:2181
    group: picker-dev
    check: false
    simplified: true
  metadata-report:
    address: zookeeper://zookeeper.grasswort.com:2181
    group: picker-dev
    retry-times: 30
    cycle-report: false
  monitor:
    protocol: registry

spring:
  dbwrappers:
    wrappers:
      - dbType: MASTER
        weight: 1
        dataSource:
          url: jdbc:mysql://39.106.71.41:3306/picker?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
          username: xuliang
          password: xol4l2y2xx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          initialSize: 2
          minIdle: 1
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,config
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          useGlobalDataSourceStat: true

      - dbType: SLAVE
        weight: 1
        dataSource:
          url: jdbc:mysql://47.93.228.48:3306/picker?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
          username: xuliang
          password: xol4l2y2xx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          initialSize: 2
          minIdle: 1
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,config
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          useGlobalDataSourceStat: true


