dubbo:
  application:
    name: picker-user-service-provider
    owner: xuliangliang
  scan:
    base-packages: com.grasswort.picker.user.service
  protocol:
    name: dubbo
    port: 20880
    serialization: kryo
  registry:
    address: nacos://nacos.grasswort.com:8848
    check: false
nacos:
  config:
    server-addr: nacos://nacos.grasswort.com:8848
    namespace: 714709d9-ff45-4e48-873f-f468f3dd90ad

spring:
  application:
    name: picker-user-service-provider
  dbwrappers:
    wrappers:
      - dbType: MASTER
        weight: 1
        dataSource:
          url: jdbc:mysql://39.106.71.41:3306/picker?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
          username: xuliang
          password: xol4l2y2xx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          initialSize: 2
          minIdle: 1
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,config
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          useGlobalDataSourceStat: true

      - dbType: SLAVE
        weight: 1
        dataSource:
          url: jdbc:mysql://47.93.228.48:3306/picker?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
          username: xuliang
          password: xol4l2y2xx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          initialSize: 2
          minIdle: 1
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,config
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          useGlobalDataSourceStat: true



