dubbo:
  application:
    name: picker-user-service-provider
    owner: xuliangliang
  protocol:
    name: dubbo
    port: 20880
  config-center:
    address: zookeeper://182.92.3.187:2181?backup=182.92.160.62:2181,39.96.42.239:2181
    group: dubbo
    check: true
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    group: picker-dev
#    check: false
#    simplified: true
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
#    group: picker-dev
#    retry-times: 30
#    cycle-report: false
#  monitor:
#    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.grasswort.picker.user.service

