spring:
  kafka:
    bootstrap-servers: 182.92.3.187:9092,182.92.160.62:9092,39.96.42.239:9092
    consumer:
      group-id: picker-email-consumer
      enable-auto-commit: false
      auto-offset-reset: latest
      max-poll-records: 100
# 邮箱设置
email:
  smtp-host: smtpdm.aliyun.com
  smtp-port: 25
  auth: true
  user: xuliangliang@notice.grasswort.com
  password: GrassworT19950422
  from-address: xuliangliang@notice.grasswort.com
  from-alias: Picker
  template-path: emailTemplate